"""Add Event table properly

Revision ID: 9a9e72f7b2bb
Revises: 8b7b1705d11b
Create Date: 2026-03-21 20:55:46.901185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9a9e72f7b2bb'
down_revision: Union[str, None] = '8b7b1705d11b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
